insert into address (street, postal_code, city) values ('3 La Follette Avenue', '95943 CEDEX 2', 'Roissy Charles-de-Gaulle');
insert into address (street, postal_code, city) values ('143 Ramsey Junction', '04109', 'Leipzig');
insert into address (street, postal_code, city) values ('96568 Warner Crossing', '10516', 'Cotuí');
insert into address (street, postal_code, city) values ('33002 Dahle Trail', null, 'Ngala');
insert into address (street, postal_code, city) values ('5 Johnson Hill', null, 'Toila');
insert into address (street, postal_code, city) values ('3 Gerald Park', '03011', 'Santa María de Jesús');
insert into address (street, postal_code, city) values ('1 4th Plaza', '132 81', 'Saltsjö-Boo');
insert into address (street, postal_code, city) values ('060 Warrior Hill', null, 'Wenxing');
insert into address (street, postal_code, city) values ('02114 Algoma Crossing', '1300', 'Kumanovo');
insert into address (street, postal_code, city) values ('0440 Shasta Terrace', '463 65', 'Nové Město pod Smrkem');
insert into address (street, postal_code, city) values ('047 Esker Point', '3505', 'Estefania');
insert into address (street, postal_code, city) values ('670 International Crossing', null, 'Anyama');
insert into address (street, postal_code, city) values ('90 Tomscot Place', null, 'Moulay Abdallah');
insert into address (street, postal_code, city) values ('28 Kingsford Circle', '48744', 'Santa Cecilia');
insert into address (street, postal_code, city) values ('9735 Melrose Road', '869-1203', 'Otaru');
insert into address (street, postal_code, city) values ('56 Myrtle Parkway', '4905-014', 'Boavista');
insert into address (street, postal_code, city) values ('9 Longview Court', '78000-000', 'Cuiabá');
insert into address (street, postal_code, city) values ('71174 Jackson Street', '95894', 'Sacramento');
insert into address (street, postal_code, city) values ('09769 Merry Parkway', '4950-850', 'Portelinha');
insert into address (street, postal_code, city) values ('3984 Merry Parkway', '9674', 'Winschoten');
insert into address (street, postal_code, city) values ('448 Summerview Point', null, 'Las Mercedes');
insert into address (street, postal_code, city) values ('88 Killdeer Center', null, 'Jingyang');
insert into address (street, postal_code, city) values ('44427 Loftsgordon Terrace', '7203', 'Sinacaban');
insert into address (street, postal_code, city) values ('9248 Truax Point', null, 'Sibubuhan');
insert into address (street, postal_code, city) values ('666 Summerview Road', null, 'Parajara');
insert into address (street, postal_code, city) values ('47 Spaight Drive', '5234', '''s-Hertogenbosch');
insert into address (street, postal_code, city) values ('36 Veith Court', '99-423', 'Bielawy');
insert into address (street, postal_code, city) values ('18488 Knutson Lane', null, 'Komarno');
insert into address (street, postal_code, city) values ('70019 Straubel Alley', '50205', 'Sámara');
insert into address (street, postal_code, city) values ('700 Duke Plaza', '62-720', 'Brudzew');
insert into address (street, postal_code, city) values ('44 South Junction', '3304', 'Garupá');
insert into address (street, postal_code, city) values ('2449 7th Crossing', '8005', 'Bansalan');
insert into address (street, postal_code, city) values ('2 Burrows Circle', null, 'Tiebiancheng');
insert into address (street, postal_code, city) values ('5 Melrose Plaza', null, 'Chengjiao');
insert into address (street, postal_code, city) values ('2 Veith Terrace', null, 'Tirmiz');
insert into address (street, postal_code, city) values ('370 Manitowish Junction', null, 'Dowan');
insert into address (street, postal_code, city) values ('503 Karstens Park', '46860', 'Virojoki');
insert into address (street, postal_code, city) values ('18332 Basil Way', null, 'Bailu');
insert into address (street, postal_code, city) values ('3 Judy Crossing', null, 'Lainqu');
insert into address (street, postal_code, city) values ('4 Clemons Way', '4990-585', 'Pousada');
insert into address (street, postal_code, city) values ('8334 American Drive', null, 'Oinoússes');
insert into address (street, postal_code, city) values ('839 Sundown Hill', '187 14', 'Täby');
insert into address (street, postal_code, city) values ('97720 Grayhawk Road', '612040', 'Svecha');
insert into address (street, postal_code, city) values ('334 Marcy Terrace', null, 'Kapenguria');
insert into address (street, postal_code, city) values ('1 Fallview Center', null, 'Tiên Phước');
insert into address (street, postal_code, city) values ('786 Mandrake Hill', '181 36', 'Lidingö');
insert into address (street, postal_code, city) values ('44 Rutledge Place', null, 'Bacem');
insert into address (street, postal_code, city) values ('65 Meadow Vale Terrace', null, 'Zaqatala');
insert into address (street, postal_code, city) values ('890 Karstens Hill', '12970-000', 'Piracaia');
insert into address (street, postal_code, city) values ('234 Heffernan Hill', null, 'Huaccana');
insert into address (street, postal_code, city) values ('655 Gale Park', null, 'El Cafetal');
insert into address (street, postal_code, city) values ('201 Lawn Parkway', '942 31', 'Älvsbyn');
insert into address (street, postal_code, city) values ('240 Fremont Alley', '981-0503', 'Yamoto');
insert into address (street, postal_code, city) values ('8 Bartelt Street', null, 'Khondāb');
insert into address (street, postal_code, city) values ('6122 American Junction', '635 01', 'Eskilstuna');
insert into address (street, postal_code, city) values ('3 Lighthouse Bay Park', null, 'Manding');
insert into address (street, postal_code, city) values ('93 Brickson Park Alley', null, 'Yitulihe');
insert into address (street, postal_code, city) values ('91 Kensington Place', null, 'Dongpu');
insert into address (street, postal_code, city) values ('8598 Brown Drive', '7534', 'Enschede');
insert into address (street, postal_code, city) values ('81617 Larry Point', null, 'Dupi');
insert into address (street, postal_code, city) values ('9 Merry Avenue', null, 'Sindangsari');
insert into address (street, postal_code, city) values ('15224 Briar Crest Way', null, 'Cipadung');
insert into address (street, postal_code, city) values ('307 Warner Way', '1219', 'Baganga');
insert into address (street, postal_code, city) values ('42 Almo Plaza', '452555', 'Semiletka');
insert into address (street, postal_code, city) values ('5312 Kenwood Drive', null, 'Matiguás');
insert into address (street, postal_code, city) values ('2 Victoria Pass', '92105', 'San Diego');
insert into address (street, postal_code, city) values ('468 Merry Lane', null, 'Bolorejo');
insert into address (street, postal_code, city) values ('841 Jackson Pass', '612425', 'Kosino');
insert into address (street, postal_code, city) values ('437 Lindbergh Trail', '88600', 'Manuel Cavazos Lerma');
insert into address (street, postal_code, city) values ('78307 Golf Course Lane', null, 'Junkou');
insert into address (street, postal_code, city) values ('0 Rowland Street', '3282', 'St. Anton an der Jeßnitz');
insert into address (street, postal_code, city) values ('64948 Farwell Alley', '232008', 'Momil');
insert into address (street, postal_code, city) values ('5 Manitowish Way', null, 'Mekarsari');
insert into address (street, postal_code, city) values ('0 Mccormick Trail', null, 'Boka');
insert into address (street, postal_code, city) values ('4127 Eliot Point', null, 'Mingshuihe');
insert into address (street, postal_code, city) values ('51597 Forest Street', null, 'Kurmuk');
insert into address (street, postal_code, city) values ('393 Mccormick Drive', '356407', 'Yelizavetinskoye');
insert into address (street, postal_code, city) values ('04859 Mccormick Junction', '4706', 'Guruyan');
insert into address (street, postal_code, city) values ('5 Sommers Crossing', null, 'Parigi');
insert into address (street, postal_code, city) values ('83548 Northview Way', null, 'Volodymyrets’');
insert into address (street, postal_code, city) values ('73139 Morningstar Avenue', '63-024', 'Krzykosy');
insert into address (street, postal_code, city) values ('2382 Monument Hill', null, 'Querobamba');
insert into address (street, postal_code, city) values ('259 American Ash Junction', '35203 CEDEX 2', 'Rennes');
insert into address (street, postal_code, city) values ('3061 Forest Dale Alley', '10039', 'New York City');
insert into address (street, postal_code, city) values ('99563 Anniversary Alley', null, 'Lianyi');
insert into address (street, postal_code, city) values ('2331 Summit Plaza', '11440', 'Ja Ela');
insert into address (street, postal_code, city) values ('77 Sunbrook Hill', '742-2807', 'Aki');
insert into address (street, postal_code, city) values ('9 Paget Junction', null, 'Malichang');
insert into address (street, postal_code, city) values ('05885 Portage Avenue', '7008', 'Payao');
insert into address (street, postal_code, city) values ('8245 Buena Vista Drive', null, 'Dhamār');
insert into address (street, postal_code, city) values ('395 Corry Circle', null, '‘Akko');
insert into address (street, postal_code, city) values ('2 Becker Point', null, 'Pohbango');
insert into address (street, postal_code, city) values ('33295 Anzinger Trail', null, 'Nanyang');
insert into address (street, postal_code, city) values ('4 Becker Street', '161396', 'Nyuksenitsa');
insert into address (street, postal_code, city) values ('86441 Coolidge Street', null, 'Fatufeto');
insert into address (street, postal_code, city) values ('8 Fieldstone Parkway', '999-3222', 'Aioi');
insert into address (street, postal_code, city) values ('36 Bunting Trail', null, 'Huangmei');
insert into address (street, postal_code, city) values ('3 Bay Park', null, 'Kebonsari Kidul');
insert into address (street, postal_code, city) values ('3099 Florence Plaza', null, 'Pale');
insert into address (street, postal_code, city) values ('6 Lillian Point', null, 'Muḩradah');
insert into address (street, postal_code, city) values ('2436 Lillian Place', '6433', 'Carhué');
insert into address (street, postal_code, city) values ('73 Fisk Park', '403964', 'Novoanninskiy');
insert into address (street, postal_code, city) values ('3315 Hansons Park', '649743', 'Turka');
insert into address (street, postal_code, city) values ('508 Schurz Street', null, 'Xarardheere');
insert into address (street, postal_code, city) values ('2 Old Shore Plaza', '77060', 'Dokri');
insert into address (street, postal_code, city) values ('7 Londonderry Trail', null, 'Dashu');
insert into address (street, postal_code, city) values ('19 Sunnyside Court', '613648', 'Stulovo');
insert into address (street, postal_code, city) values ('26 Lighthouse Bay Trail', '4602', 'Talisay');
insert into address (street, postal_code, city) values ('241 Ilene Point', null, 'Novi Itebej');
insert into address (street, postal_code, city) values ('66996 Mcbride Drive', '144 30', 'Rönninge');
insert into address (street, postal_code, city) values ('15267 Anthes Alley', '73-120', 'Chociwel');
insert into address (street, postal_code, city) values ('95130 Manufacturers Point', '10550', 'Pulau Pinang');
insert into address (street, postal_code, city) values ('2 Blue Bill Park Point', '357128', 'Nevinnomyssk');
insert into address (street, postal_code, city) values ('0 Rutledge Crossing', null, 'Dananshan');
insert into address (street, postal_code, city) values ('00 Fordem Plaza', null, 'Shimen');
insert into address (street, postal_code, city) values ('66311 Eliot Court', null, 'Longba');
insert into address (street, postal_code, city) values ('1137 Manitowish Alley', '9970-244', 'Fazenda de Santa Cruz');
insert into address (street, postal_code, city) values ('33 Harper Junction', null, 'Arjawinangun');
insert into address (street, postal_code, city) values ('9 Leroy Way', null, 'Boroko');
insert into address (street, postal_code, city) values ('3335 Bartelt Court', null, 'Hiseti');
insert into address (street, postal_code, city) values ('3 Meadow Ridge Drive', '1033', 'Kathu');
insert into address (street, postal_code, city) values ('64396 Hauk Junction', null, 'Farriar');
insert into address (street, postal_code, city) values ('1225 Raven Circle', '18-421', 'Piątnica');
insert into address (street, postal_code, city) values ('674 Aberg Avenue', null, 'Rusip');
insert into address (street, postal_code, city) values ('19 Eagan Center', '827 24', 'Ljusdal');
insert into address (street, postal_code, city) values ('269 Lunder Crossing', null, 'San Agustin');
insert into address (street, postal_code, city) values ('36 Daystar Way', '6313', 'Mabini');
insert into address (street, postal_code, city) values ('04614 Washington Court', null, 'Banjar Bau Kawan');
insert into address (street, postal_code, city) values ('14 Kipling Plaza', '16000-000', 'Araçatuba');
insert into address (street, postal_code, city) values ('99 Starling Terrace', '607069', 'Vyksa');
insert into address (street, postal_code, city) values ('4732 Duke Drive', null, 'San José de Colinas');
insert into address (street, postal_code, city) values ('5951 Badeau Trail', null, 'Guli');
insert into address (street, postal_code, city) values ('93291 Kim Crossing', null, 'Trogan Barat');
insert into address (street, postal_code, city) values ('50 Mallard Court', null, 'Banjar Sengguan');
insert into address (street, postal_code, city) values ('9 Golf View Plaza', null, 'Wuli');
insert into address (street, postal_code, city) values ('71874 Eagle Crest Circle', '48280-000', 'Mata de São João');
insert into address (street, postal_code, city) values ('3533 Leroy Trail', '427531', 'Shchukino');
insert into address (street, postal_code, city) values ('8 La Follette Street', 'G8A', 'Casselman');
insert into address (street, postal_code, city) values ('06 Leroy Trail', '787-0150', 'Isawa');
insert into address (street, postal_code, city) values ('70 Brickson Park Place', null, 'Ol Kalou');
insert into address (street, postal_code, city) values ('055 Haas Court', null, 'Ilandža');
insert into address (street, postal_code, city) values ('902 Oak Lane', null, 'Sukasirna');
insert into address (street, postal_code, city) values ('10429 Cordelia Court', '28300-000', 'Itaperuna');
insert into address (street, postal_code, city) values ('42 Ramsey Center', null, 'Janja');
insert into address (street, postal_code, city) values ('0568 Nobel Pass', '457654', 'Parizh');
insert into address (street, postal_code, city) values ('340 Crowley Lane', '412950', 'Shikhany');
insert into address (street, postal_code, city) values ('0983 Redwing Park', null, 'Maikawada');
insert into address (street, postal_code, city) values ('702 Morningstar Terrace', '68510', 'Lincoln');
insert into address (street, postal_code, city) values ('307 Chive Terrace', null, 'Hejiayan');
insert into address (street, postal_code, city) values ('8 Drewry Junction', '611 35', 'Nyköping');
insert into address (street, postal_code, city) values ('1 Carpenter Terrace', '216646', 'Nizhnyaya Tura');
insert into address (street, postal_code, city) values ('5 Glacier Hill Street', null, 'Yolöten');
insert into address (street, postal_code, city) values ('6791 Hintze Way', 'L-9651', 'Eschweiler');
insert into address (street, postal_code, city) values ('391 Center Circle', '764517', 'Buenaventura');
insert into address (street, postal_code, city) values ('3536 Dayton Center', null, 'Watsa');
insert into address (street, postal_code, city) values ('6 Mosinee Avenue', '1752', 'Las Piñas');
insert into address (street, postal_code, city) values ('99 Straubel Street', null, 'Wukari');
insert into address (street, postal_code, city) values ('46293 Ronald Regan Lane', null, 'Gujiang');
insert into address (street, postal_code, city) values ('423 Waubesa Center', null, 'Bonabéri');
insert into address (street, postal_code, city) values ('90 Northport Drive', null, 'Trinity');
insert into address (street, postal_code, city) values ('03 Ohio Alley', null, 'Kroya');
insert into address (street, postal_code, city) values ('360 Forest Run Lane', null, 'Yangqiao');
insert into address (street, postal_code, city) values ('43 Graedel Parkway', null, 'Talun');
insert into address (street, postal_code, city) values ('0188 4th Trail', '0748', 'North Shore');
insert into address (street, postal_code, city) values ('9 Tomscot Road', '25330', 'Kuusjoki');
insert into address (street, postal_code, city) values ('86 Monterey Circle', null, 'Dashtobod');
insert into address (street, postal_code, city) values ('01951 Schurz Way', null, 'Jiangjia');
insert into address (street, postal_code, city) values ('3976 Calypso Park', null, 'Mekarsari');
insert into address (street, postal_code, city) values ('5778 Scott Lane', '171 64', 'Solna');
insert into address (street, postal_code, city) values ('3042 Evergreen Street', '72118', 'North Little Rock');
insert into address (street, postal_code, city) values ('33899 Schmedeman Plaza', null, 'Cairima');
insert into address (street, postal_code, city) values ('61796 Dapin Crossing', null, 'Yangjian');
insert into address (street, postal_code, city) values ('90354 Browning Parkway', '8501', 'San Francisco');
insert into address (street, postal_code, city) values ('9781 Namekagon Court', '80804', 'München');
insert into address (street, postal_code, city) values ('595 Mcbride Street', '38126', 'Braunschweig');
insert into address (street, postal_code, city) values ('8055 Columbus Alley', null, 'Nanyang');
insert into address (street, postal_code, city) values ('3 Hovde Terrace', '989-2474', 'Asahi');
insert into address (street, postal_code, city) values ('9579 Westend Center', null, 'Bondoukou');
insert into address (street, postal_code, city) values ('9 Jenifer Park', null, 'Sebulu');
insert into address (street, postal_code, city) values ('80 Mccormick Drive', null, 'Samparna');
insert into address (street, postal_code, city) values ('60 Oakridge Parkway', null, 'Santa Cruz de Guacas');
insert into address (street, postal_code, city) values ('61613 Farragut Place', '75620-000', 'Pontalina');
insert into address (street, postal_code, city) values ('9886 Green Ridge Terrace', null, 'Cibeureum');
insert into address (street, postal_code, city) values ('65451 Ronald Regan Street', null, 'Jiji');
insert into address (street, postal_code, city) values ('06328 Kings Junction', null, 'Liudaogou');
insert into address (street, postal_code, city) values ('320 Fulton Avenue', null, 'Liaoyang');
insert into address (street, postal_code, city) values ('25472 Nevada Place', null, 'Xikou');
insert into address (street, postal_code, city) values ('5231 Lien Terrace', '429337', 'Kanash');
insert into address (street, postal_code, city) values ('956 Sullivan Way', null, 'Bakan');
insert into address (street, postal_code, city) values ('5 Boyd Avenue', 'MD-5233', 'Drochia');
insert into address (street, postal_code, city) values ('718 Columbus Court', '369228', 'Ordzhonikidzevskiy');
insert into address (street, postal_code, city) values ('49771 Mendota Pass', '2000-452', 'Alqueidão');
insert into address (street, postal_code, city) values ('0 Stuart Crossing', '35540', 'Juupajoki');
insert into address (street, postal_code, city) values ('5087 Welch Alley', null, 'Balesari');
insert into address (street, postal_code, city) values ('145 Pepper Wood Trail', null, 'Hudong');
insert into address (street, postal_code, city) values ('24 Granby Court', '78067 CEDEX', 'Saint-Quentin-en-Yvelines');
insert into address (street, postal_code, city) values ('65 Transport Drive', null, 'Arwād');
insert into address (street, postal_code, city) values ('31 Corben Court', '3384', 'Montecarlo');
insert into address (street, postal_code, city) values ('237 Vera Plaza', '649780', 'Kosh-Agach');
insert into address (street, postal_code, city) values ('670 Loftsgordon Lane', null, 'Nangewer');
insert into address (street, postal_code, city) values ('6935 Ronald Regan Circle', null, 'Broshniv-Osada');
insert into address (street, postal_code, city) values ('13 Vera Lane', null, 'Luodian');
insert into address (street, postal_code, city) values ('7 Bluestem Center', '763008', 'Andalucía');
insert into address (street, postal_code, city) values ('12800 Karstens Trail', null, 'Jianyangping');
insert into address (street, postal_code, city) values ('97640 Golf View Drive', '05-816', 'Michałowice');
insert into address (street, postal_code, city) values ('1970 Glacier Hill Court', null, 'Huacrapuquio');
insert into address (street, postal_code, city) values ('03 Delaware Avenue', '9400', 'Bella Vista');
insert into address (street, postal_code, city) values ('70986 Eastlawn Court', null, 'Agdzhabedy');
insert into address (street, postal_code, city) values ('00203 Artisan Hill', null, 'Hongyan');
insert into address (street, postal_code, city) values ('4 Dorton Way', '544529', 'Cucutilla');
insert into address (street, postal_code, city) values ('25296 Bowman Place', null, 'Bianba');
insert into address (street, postal_code, city) values ('55 Kinsman Pass', null, 'Xinxu');
insert into address (street, postal_code, city) values ('0 Village Terrace', '22304 CEDEX', 'Lannion');
insert into address (street, postal_code, city) values ('72194 Warner Center', null, 'Avlónas');
insert into address (street, postal_code, city) values ('61118 Anthes Alley', null, 'Salamwates');
insert into address (street, postal_code, city) values ('55033 Coleman Crossing', null, 'Strenči');
insert into address (street, postal_code, city) values ('4 Blackbird Circle', null, 'Tongjing');
insert into address (street, postal_code, city) values ('23 Muir Court', '89270-000', 'Guaramirim');
insert into address (street, postal_code, city) values ('13 Memorial Trail', '30110', 'Phimai');
insert into address (street, postal_code, city) values ('2957 Ramsey Place', null, 'Shibli');
insert into address (street, postal_code, city) values ('9738 Carpenter Street', null, 'Gelatik');
insert into address (street, postal_code, city) values ('137 Coleman Street', null, 'Kampala');
insert into address (street, postal_code, city) values ('3 Troy Street', null, 'Bojong');
insert into address (street, postal_code, city) values ('92848 Warner Hill', null, 'Pangansalan');
insert into address (street, postal_code, city) values ('300 Ridgeway Court', null, 'Tangchi');
insert into address (street, postal_code, city) values ('15 Homewood Pass', null, 'Zahlé');
insert into address (street, postal_code, city) values ('08 Di Loreto Avenue', null, 'Thị Trấn Ngọc Lặc');
insert into address (street, postal_code, city) values ('660 Fisk Way', null, 'Sukamaju');
insert into address (street, postal_code, city) values ('347 Chive Street', null, 'Canggetelo');
insert into address (street, postal_code, city) values ('21 Hayes Circle', '43-365', 'Wilkowice');
insert into address (street, postal_code, city) values ('2783 Rockefeller Drive', '476048', 'Pedraza');
insert into address (street, postal_code, city) values ('998 Summit Junction', null, 'Orguz');
insert into address (street, postal_code, city) values ('3193 Esker Court', null, 'Illushi');
insert into address (street, postal_code, city) values ('2996 Montana Junction', '35660-000', 'Pará de Minas');
insert into address (street, postal_code, city) values ('3 Lindbergh Center', null, 'Ma’an');
insert into address (street, postal_code, city) values ('771 Hagan Plaza', null, 'Balykchy');
insert into address (street, postal_code, city) values ('96 Mccormick Parkway', '0017', 'Oslo');
insert into address (street, postal_code, city) values ('46 Rockefeller Street', null, 'Maubara');
insert into address (street, postal_code, city) values ('6677 Artisan Street', null, 'Kawengan');
insert into address (street, postal_code, city) values ('0 Loomis Parkway', null, 'Panawuan');
insert into address (street, postal_code, city) values ('3 Bobwhite Junction', '20270', 'Lue Amnat');
insert into address (street, postal_code, city) values ('32 Schurz Park', null, 'Agua Buena');
insert into address (street, postal_code, city) values ('5 Caliangt Street', '7740', 'Veliki Preslav');
insert into address (street, postal_code, city) values ('40 Maple Junction', '055038', 'Abejorral');
insert into address (street, postal_code, city) values ('38007 Huxley Trail', null, 'Sake');
insert into address (street, postal_code, city) values ('66304 Blue Bill Park Circle', '301113', 'Slobodka');
insert into address (street, postal_code, city) values ('6 Meadow Valley Circle', null, 'Caoxi');
insert into address (street, postal_code, city) values ('08278 Nova Road', null, 'Nanying');
insert into address (street, postal_code, city) values ('568 Sachtjen Parkway', '459 30', 'Ljungskile');
insert into address (street, postal_code, city) values ('26786 Little Fleur Lane', '13510-000', 'Santa Gertrudes');
insert into address (street, postal_code, city) values ('7223 Comanche Plaza', '687 22', 'Ostrožská Nová Ves');
insert into address (street, postal_code, city) values ('73938 Brentwood Way', '8201', 'Veinticinco de Mayo');
insert into address (street, postal_code, city) values ('48559 Cordelia Road', null, 'Xinan');
insert into address (street, postal_code, city) values ('4843 Anniversary Parkway', '164 35', 'Kista');
insert into address (street, postal_code, city) values ('040 Derek Hill', null, 'Uripa');
insert into address (street, postal_code, city) values ('0 Mccormick Way', '75220 CEDEX 16', 'Paris 16');
insert into address (street, postal_code, city) values ('00 Ruskin Alley', null, 'Condega');
insert into address (street, postal_code, city) values ('1438 John Wall Avenue', '85072', 'Phoenix');
insert into address (street, postal_code, city) values ('09785 Amoth Place', '135 22', 'Tyresö');
insert into address (street, postal_code, city) values ('82672 David Hill', '629309', 'Novyy Urengoy');
insert into address (street, postal_code, city) values ('279 Rusk Court', null, 'Stari Bohorodchany');
insert into address (street, postal_code, city) values ('998 Packers Plaza', '99047', 'Rusnė');
insert into address (street, postal_code, city) values ('3 Morrow Point', '96960', 'Ailuk');
insert into address (street, postal_code, city) values ('37 Towne Alley', null, 'Puunage');
insert into address (street, postal_code, city) values ('4138 Fulton Alley', '44159 CEDEX', 'Ancenis');
insert into address (street, postal_code, city) values ('27 Fairfield Lane', null, 'Bantilan');
insert into address (street, postal_code, city) values ('6 Lawn Avenue', '396310', 'Novaya Usman’');
insert into address (street, postal_code, city) values ('960 Caliangt Terrace', null, 'Yuanmou');
insert into address (street, postal_code, city) values ('4 Farwell Junction', null, 'Khenifra');
insert into address (street, postal_code, city) values ('40913 Havey Circle', '253627', 'Nocaima');
insert into address (street, postal_code, city) values ('770 Melby Road', null, 'Suchen');
insert into address (street, postal_code, city) values ('73 Jackson Junction', null, 'Al Mughayyir');
insert into address (street, postal_code, city) values ('518 Larry Center', null, 'Brongkalan');
insert into address (street, postal_code, city) values ('23194 Pond Hill', null, 'Évlalo');
insert into address (street, postal_code, city) values ('185 Elmside Drive', '4515', 'Jovellar');
insert into address (street, postal_code, city) values ('22699 Westridge Avenue', null, 'Zarrīn Shahr');
insert into address (street, postal_code, city) values ('2 Bashford Road', null, 'Huashi');
insert into address (street, postal_code, city) values ('10 Huxley Drive', '9021', 'Libertad');
insert into address (street, postal_code, city) values ('3383 Arizona Junction', 'V5Y', 'Ferme-Neuve');
insert into address (street, postal_code, city) values ('8757 Coolidge Way', '416067', 'La Plata');
insert into address (street, postal_code, city) values ('14571 Buhler Alley', null, 'Chumen');
insert into address (street, postal_code, city) values ('814 Grim Junction', '35400', 'Ljupina');
insert into address (street, postal_code, city) values ('47849 Warner Place', 'P1A', 'North Bay');
insert into address (street, postal_code, city) values ('9733 Bay Junction', '28355', 'Bremen');
insert into address (street, postal_code, city) values ('39420 Fairfield Lane', '426-0025', 'Fujieda');
insert into address (street, postal_code, city) values ('70 South Place', null, 'Dongshandi');
insert into address (street, postal_code, city) values ('89302 Melrose Drive', null, 'Canaries');
insert into address (street, postal_code, city) values ('9 Mcguire Avenue', null, 'Linglong');
insert into address (street, postal_code, city) values ('296 Novick Place', '2950-577', 'Pinhal da Marquesa');
insert into address (street, postal_code, city) values ('5 Helena Way', '999-7681', 'Hirakata');
insert into address (street, postal_code, city) values ('3 Texas Place', '624400', 'Novaya Lyalya');
insert into address (street, postal_code, city) values ('133 Express Terrace', null, 'Leworook');
insert into address (street, postal_code, city) values ('8904 Green Junction', '16130', 'Bang Racham');
insert into address (street, postal_code, city) values ('754 Amoth Junction', '10016', 'San Juan Bautista');
insert into address (street, postal_code, city) values ('3 Delladonna Center', null, 'Tocumen');
insert into address (street, postal_code, city) values ('51 Colorado Trail', null, 'Quebradas');
insert into address (street, postal_code, city) values ('8 Buhler Crossing', '38300-000', 'Ituiutaba');
insert into address (street, postal_code, city) values ('289 Eastwood Drive', '4795-193', 'Roriz');
insert into address (street, postal_code, city) values ('93006 Esch Lane', '5246', 'Rojas');
insert into address (street, postal_code, city) values ('1 Brentwood Pass', null, 'Arrah');
insert into address (street, postal_code, city) values ('6 Blaine Junction', null, 'Dhamār');
insert into address (street, postal_code, city) values ('728 Nova Parkway', null, 'Cajamarca');
insert into address (street, postal_code, city) values ('6638 Cambridge Street', null, 'Erími');
insert into address (street, postal_code, city) values ('5 Mccormick Circle', null, 'Karangturi');
insert into address (street, postal_code, city) values ('0 Vernon Hill', null, 'Jabon');
insert into address (street, postal_code, city) values ('3 3rd Point', '85227', 'San Jose');
insert into address (street, postal_code, city) values ('1 Huxley Parkway', null, 'Mukacheve');
insert into address (street, postal_code, city) values ('90023 Stephen Park', null, 'Vareiá');
insert into address (street, postal_code, city) values ('26677 Independence Street', null, 'Koubia');
insert into address (street, postal_code, city) values ('411 Amoth Road', '34829', 'Merkezköy');
insert into address (street, postal_code, city) values ('0316 Kinsman Hill', '6406', 'Victoria');
insert into address (street, postal_code, city) values ('19 Kings Avenue', null, 'Mangulewa');
insert into address (street, postal_code, city) values ('55811 Cascade Point', null, 'Thị Trấn Mường Khến');
insert into address (street, postal_code, city) values ('7 Hansons Alley', null, 'Chornukhyne');
insert into address (street, postal_code, city) values ('09656 New Castle Alley', null, 'Şafāshahr');
insert into address (street, postal_code, city) values ('7335 Farragut Plaza', null, 'Kampong Thom');
insert into address (street, postal_code, city) values ('73687 Heffernan Hill', '42020', 'Harnoli');
insert into address (street, postal_code, city) values ('115 Karstens Center', '5644', 'Eindhoven');
insert into address (street, postal_code, city) values ('1 Dapin Street', '48000', 'Nakhon Phanom');
insert into address (street, postal_code, city) values ('07 Oak Valley Point', null, 'Jiapeng');
insert into address (street, postal_code, city) values ('9734 Manufacturers Pass', '98000', 'La Condamine');
insert into address (street, postal_code, city) values ('470 2nd Road', null, 'Tanahmerah');
insert into address (street, postal_code, city) values ('03 Fairview Hill', '79240-000', 'Jardim');
insert into address (street, postal_code, city) values ('3282 Fairview Park', '06-302', 'Przasnysz');
insert into address (street, postal_code, city) values ('311 Village Plaza', null, 'Hechuan');
insert into address (street, postal_code, city) values ('93 Monica Park', '270-0164', 'Nagareyama');
insert into address (street, postal_code, city) values ('1 Valley Edge Road', null, 'Tuoshi');
insert into address (street, postal_code, city) values ('79 Clove Plaza', '43180', 'Phon Charoen');
insert into address (street, postal_code, city) values ('302 Hayes Circle', null, 'Ulster Spring');
insert into address (street, postal_code, city) values ('8192 Northland Circle', null, 'Sanjie');
insert into address (street, postal_code, city) values ('71 Arapahoe Road', '34643', 'Largo');
insert into address (street, postal_code, city) values ('68 Walton Place', null, 'Mantingantengah');
insert into address (street, postal_code, city) values ('41 Hagan Way', null, 'Rancaseneng');
insert into address (street, postal_code, city) values ('502 Waubesa Terrace', null, 'Vurğun');
insert into address (street, postal_code, city) values ('56 Waywood Trail', '3400-044', 'Gramaços');
insert into address (street, postal_code, city) values ('33460 Macpherson Terrace', null, 'Liuzhou');
insert into address (street, postal_code, city) values ('5 6th Plaza', null, 'Kuafeu');
insert into address (street, postal_code, city) values ('430 Gerald Junction', '0802', 'Bulasa');
insert into address (street, postal_code, city) values ('82641 Bashford Plaza', '739 47', 'Kozlovice');
insert into address (street, postal_code, city) values ('01786 Anniversary Place', '91229 CEDEX', 'Brétigny-sur-Orge');
insert into address (street, postal_code, city) values ('1 Becker Street', null, 'Yong’an');
insert into address (street, postal_code, city) values ('803 Heath Drive', '249360', 'Khvastovichi');
insert into address (street, postal_code, city) values ('0439 Victoria Lane', '734048', 'Cunday');
insert into address (street, postal_code, city) values ('498 Kings Place', null, 'Liangbing');
insert into address (street, postal_code, city) values ('94 Anzinger Park', '66205', 'Shawnee Mission');
insert into address (street, postal_code, city) values ('723 Golf Course Center', null, 'San Lorenzo de Esmeraldas');
insert into address (street, postal_code, city) values ('75 Menomonie Avenue', '9401', 'Batasan');
insert into address (street, postal_code, city) values ('9023 Prentice Alley', null, 'Taman');
insert into address (street, postal_code, city) values ('6691 Northwestern Crossing', '3706', 'Mabua');
insert into address (street, postal_code, city) values ('69 Mcguire Alley', '03017', 'San Miguel Dueñas');
insert into address (street, postal_code, city) values ('13 Green Ridge Lane', null, 'Rongkou');
insert into address (street, postal_code, city) values ('47483 Tomscot Road', null, 'Tlogosadang');
insert into address (street, postal_code, city) values ('9052 Milwaukee Crossing', null, 'Xi’an');
insert into address (street, postal_code, city) values ('18020 Bunker Hill Junction', '7300', 'Iraray');
insert into address (street, postal_code, city) values ('02 Hansons Road', '79160', 'Kandhkot');
insert into address (street, postal_code, city) values ('4671 Sommers Lane', 'L9T', 'Milton');
insert into address (street, postal_code, city) values ('3434 Canary Pass', '78685-000', 'Araguaiana');
insert into address (street, postal_code, city) values ('36975 Meadow Vale Circle', null, 'Qiansuo');
insert into address (street, postal_code, city) values ('1622 Oriole Lane', null, 'Al Jīzah');
insert into address (street, postal_code, city) values ('81 Harbort Junction', '4162', 'La Cocha');
insert into address (street, postal_code, city) values ('53609 Loomis Street', '682574', 'Sokol');
insert into address (street, postal_code, city) values ('6 Texas Center', null, 'Jiquinlaca');
insert into address (street, postal_code, city) values ('18565 Mandrake Way', '40231', 'Jahāniān Shāh');
insert into address (street, postal_code, city) values ('93751 Green Alley', null, 'Lucun');
insert into address (street, postal_code, city) values ('2779 Lerdahl Place', null, 'Denpasar');
insert into address (street, postal_code, city) values ('93 Waxwing Court', null, 'Los Ángeles');
insert into address (street, postal_code, city) values ('010 Pine View Hill', '13160', 'Bang Pa-in');
insert into address (street, postal_code, city) values ('5 Gina Parkway', null, 'Kai');
insert into address (street, postal_code, city) values ('0731 Clarendon Parkway', null, 'Tielu');
insert into address (street, postal_code, city) values ('53543 Aberg Drive', '09116', 'Chemnitz');
insert into address (street, postal_code, city) values ('75835 Brentwood Terrace', '29220', 'Columbia');
insert into address (street, postal_code, city) values ('32222 Anniversary Plaza', '739 84', 'Bukovec');
insert into address (street, postal_code, city) values ('2270 Trailsway Point', null, 'Busan');
insert into address (street, postal_code, city) values ('824 East Court', '90036', 'Plateliai');
insert into address (street, postal_code, city) values ('08117 Forest Run Circle', null, 'Kasempa');
insert into address (street, postal_code, city) values ('5 Sundown Way', null, 'Mzuzu');
insert into address (street, postal_code, city) values ('72 Summer Ridge Park', '438 01', 'Nové Sedlo');
insert into address (street, postal_code, city) values ('50860 Lien Circle', null, 'Dampit Satu');
insert into address (street, postal_code, city) values ('45394 Morningstar Trail', '80240', 'Hikkaduwa');
insert into address (street, postal_code, city) values ('8 Lillian Place', null, 'Dhuusamarreeb');
insert into address (street, postal_code, city) values ('93 Sunfield Terrace', null, 'Liwonde');
insert into address (street, postal_code, city) values ('4 Pleasure Court', null, 'Skotoússa');
insert into address (street, postal_code, city) values ('493 Nobel Place', null, 'Shanlian');
insert into address (street, postal_code, city) values ('4632 Westport Court', '84977 CEDEX', 'Carpentras');
insert into address (street, postal_code, city) values ('95440 Gulseth Hill', '691 41', 'Karlskoga');
insert into address (street, postal_code, city) values ('2 Donald Crossing', null, 'Salamá');
insert into address (street, postal_code, city) values ('83 Tony Trail', null, 'Huanxi');
insert into address (street, postal_code, city) values ('6982 Dwight Pass', '671360', 'Bichura');
insert into address (street, postal_code, city) values ('37 Hauk Point', '4990-585', 'Pousada');
insert into address (street, postal_code, city) values ('47 Eagle Crest Plaza', '05-806', 'Komorów');
insert into address (street, postal_code, city) values ('914 Armistice Road', null, 'Kuwayris Sharqī');
insert into address (street, postal_code, city) values ('90878 Stone Corner Center', null, 'Partang');
insert into address (street, postal_code, city) values ('17 Lakewood Gardens Trail', '3102', 'Nugas');
insert into address (street, postal_code, city) values ('194 Mccormick Pass', '164010', 'Konosha');
insert into address (street, postal_code, city) values ('91728 Sunnyside Terrace', '353159', 'Gostilitsy');
insert into address (street, postal_code, city) values ('797 5th Parkway', null, 'Delgado');
insert into address (street, postal_code, city) values ('74 Montana Junction', '2704', 'Narvacan');
insert into address (street, postal_code, city) values ('21 Springview Pass', '40000', 'Jaffna');
insert into address (street, postal_code, city) values ('49102 Armistice Junction', null, 'Shuangqiao');
insert into address (street, postal_code, city) values ('308 Melvin Street', '506 40', 'Borås');
insert into address (street, postal_code, city) values ('9367 Northview Hill', null, 'Daru');
insert into address (street, postal_code, city) values ('6313 Myrtle Center', null, 'Huaping');
insert into address (street, postal_code, city) values ('02 Upham Pass', null, 'Calibishie');
insert into address (street, postal_code, city) values ('3771 Ramsey Hill', '10141', 'Torino');
insert into address (street, postal_code, city) values ('589 Fairfield Lane', '956-0123', 'Suita');
insert into address (street, postal_code, city) values ('056 Carey Street', null, 'Luchingu');
insert into address (street, postal_code, city) values ('56378 Aberg Junction', null, 'Polje');
insert into address (street, postal_code, city) values ('0159 Lunder Way', null, 'Emplak');
insert into address (street, postal_code, city) values ('3 Raven Street', '969-3288', 'Inawashiro');
insert into address (street, postal_code, city) values ('62 Jackson Parkway', null, 'Balaklava');
insert into address (street, postal_code, city) values ('42 Arkansas Terrace', '055028', 'La Unión');
insert into address (street, postal_code, city) values ('3 Gale Street', null, 'Wenchang');
insert into address (street, postal_code, city) values ('80 Browning Plaza', '2785-366', 'Matarraque');
insert into address (street, postal_code, city) values ('64284 Lakewood Gardens Center', null, 'Ayo');
insert into address (street, postal_code, city) values ('69 Corry Circle', null, 'Al Ya‘rubīyah');
insert into address (street, postal_code, city) values ('51708 Springs Road', '65213-000', 'Penalva');
insert into address (street, postal_code, city) values ('519 Colorado Junction', '3330-304', 'Góis');
insert into address (street, postal_code, city) values ('2985 Florence Lane', '391357', 'Pechenga');
insert into address (street, postal_code, city) values ('8 Vera Lane', null, 'Abū Tīj');
insert into address (street, postal_code, city) values ('84 Summer Ridge Terrace', '3604', 'Thun');
insert into address (street, postal_code, city) values ('27 Autumn Leaf Road', null, 'Yejia');
insert into address (street, postal_code, city) values ('32 Commercial Park', null, 'Gaoqiao');
insert into address (street, postal_code, city) values ('67 Arapahoe Court', null, 'Asempapak');
insert into address (street, postal_code, city) values ('107 Ramsey Avenue', null, 'Pesagen');
insert into address (street, postal_code, city) values ('14 Pawling Place', '3302', 'Communal');
insert into address (street, postal_code, city) values ('2 Graedel Junction', '253017', 'Facatativá');
insert into address (street, postal_code, city) values ('0441 Truax Parkway', null, 'Kolympári');
insert into address (street, postal_code, city) values ('642 Colorado Place', null, 'Horokhiv');
insert into address (street, postal_code, city) values ('27065 Spohn Junction', null, 'Guanban');
insert into address (street, postal_code, city) values ('5 Dottie Circle', '84019 CEDEX 1', 'Avignon');
insert into address (street, postal_code, city) values ('36351 3rd Street', '94723', 'Petrolera');
insert into address (street, postal_code, city) values ('8 Cody Way', '65951 CEDEX 9', 'Tarbes');
insert into address (street, postal_code, city) values ('9711 Tennessee Drive', null, 'Huimin');
insert into address (street, postal_code, city) values ('7 Sachs Junction', '655138', 'Chernogorsk');
insert into address (street, postal_code, city) values ('67676 Ridge Oak Lane', null, 'Dadianzi');
insert into address (street, postal_code, city) values ('76798 Helena Trail', '13000-000', 'Campinas');
insert into address (street, postal_code, city) values ('18 Dennis Point', null, 'Xinghua');
insert into address (street, postal_code, city) values ('50998 Little Fleur Park', null, 'Changchi');
insert into address (street, postal_code, city) values ('65 International Street', '9504', 'Polomolok');
insert into address (street, postal_code, city) values ('7 Ridge Oak Terrace', '6700', 'Catbalogan');
insert into address (street, postal_code, city) values ('1 Maple Drive', '633411', 'Gornyy');
insert into address (street, postal_code, city) values ('99028 Clyde Gallagher Pass', null, 'Wucun');
insert into address (street, postal_code, city) values ('74 Hazelcrest Park', '658065', 'Borovikha');
insert into address (street, postal_code, city) values ('5915 Birchwood Pass', '34-625', 'Skrzydlna');
insert into address (street, postal_code, city) values ('62 Elka Junction', '382 08', 'Chvalšiny');
insert into address (street, postal_code, city) values ('317 Killdeer Parkway', '50109 CEDEX', 'Cherbourg-Octeville');
insert into address (street, postal_code, city) values ('45 Elgar Place', null, 'Mertani');
insert into address (street, postal_code, city) values ('49623 Anthes Avenue', null, 'Kayangel');
insert into address (street, postal_code, city) values ('03 Oakridge Circle', '2405', 'Carot');
insert into address (street, postal_code, city) values ('800 Golf View Alley', null, 'Tiancheng');
insert into address (street, postal_code, city) values ('90 Elmside Drive', null, 'Serhetabat');
insert into address (street, postal_code, city) values ('10 Granby Plaza', null, 'Anávra');
insert into address (street, postal_code, city) values ('5 Shopko Trail', null, 'Yingkeng');
insert into address (street, postal_code, city) values ('7 Del Sol Drive', null, 'Fenshui');
insert into address (street, postal_code, city) values ('49491 Spaight Circle', null, 'Hanyin Chengguanzhen');
insert into address (street, postal_code, city) values ('3 Eastlawn Circle', null, 'Vailoa');
insert into address (street, postal_code, city) values ('5869 Grasskamp Drive', '425090', 'Krasnogorskiy');
insert into address (street, postal_code, city) values ('474 Annamark Alley', 'T8S', 'Peace River');
insert into address (street, postal_code, city) values ('0200 Hoard Center', null, 'Cibeusi');
insert into address (street, postal_code, city) values ('00 Vermont Court', null, 'Watodei');
insert into address (street, postal_code, city) values ('4212 Forest Run Avenue', '42301', 'Jämsänkoski');
insert into address (street, postal_code, city) values ('7868 Talmadge Road', null, 'Padangsidempuan');
insert into address (street, postal_code, city) values ('21 Reindahl Place', '1109', 'Malaga');
insert into address (street, postal_code, city) values ('2401 Sachs Terrace', null, 'Georgetown');
insert into address (street, postal_code, city) values ('2258 Veith Way', '307156', 'Zheleznogorsk');
insert into address (street, postal_code, city) values ('0501 Memorial Park', null, 'Majzar');
insert into address (street, postal_code, city) values ('7 Cardinal Lane', '06357 CEDEX 4', 'Nice');
insert into address (street, postal_code, city) values ('360 Brown Junction', '4585-254', 'Parada de Todeia');
insert into address (street, postal_code, city) values ('7171 Prairie Rose Point', '3515-626', 'Silgueiros');
insert into address (street, postal_code, city) values ('4 Packers Point', null, 'Longgang');
insert into address (street, postal_code, city) values ('9 Kinsman Park', '59-171', 'Przemków');
insert into address (street, postal_code, city) values ('60 Coolidge Avenue', '17314 CEDEX', 'Rochefort');
insert into address (street, postal_code, city) values ('4638 Talisman Plaza', null, 'Guolemude');
insert into address (street, postal_code, city) values ('59915 Shelley Crossing', null, 'Anibare');
insert into address (street, postal_code, city) values ('933 Old Gate Hill', null, 'Montijo');
insert into address (street, postal_code, city) values ('95 Colorado Plaza', '9272', 'Devnya');
insert into address (street, postal_code, city) values ('3253 Kensington Hill', '366510', 'Urus-Martan');
insert into address (street, postal_code, city) values ('86576 Carberry Park', '671732', 'Novyy Uoyan');
insert into address (street, postal_code, city) values ('52451 Shasta Court', null, 'Mengdong');
insert into address (street, postal_code, city) values ('62 La Follette Point', null, 'Zeqin');
insert into address (street, postal_code, city) values ('33 Warrior Street', '168020', 'Kortkeros');
insert into address (street, postal_code, city) values ('816 Spohn Avenue', null, 'Hongqi');
insert into address (street, postal_code, city) values ('4 Pond Lane', null, 'Banpu');
insert into address (street, postal_code, city) values ('3 Golf Course Trail', null, 'Trstenik');
insert into address (street, postal_code, city) values ('18 Anthes Terrace', null, 'Afántou');
insert into address (street, postal_code, city) values ('28 Westerfield Park', '63-405', 'Sieroszewice');
insert into address (street, postal_code, city) values ('63 Swallow Avenue', '8800-114', 'Luz de Tavira');
insert into address (street, postal_code, city) values ('4792 Larry Way', '20380', 'Washington');
insert into address (street, postal_code, city) values ('4 Northport Lane', null, 'Baki');
insert into address (street, postal_code, city) values ('4772 Sunfield Road', '95-010', 'Stryków');
insert into address (street, postal_code, city) values ('569 Pierstorff Circle', null, 'Bajingzi');
insert into address (street, postal_code, city) values ('11517 Nevada Parkway', null, 'Anrong');
insert into address (street, postal_code, city) values ('09553 Rockefeller Alley', null, 'Namayingo');
insert into address (street, postal_code, city) values ('2 Hoard Road', null, 'Almaty');
insert into address (street, postal_code, city) values ('9 Ridgeview Center', '6329', 'Lacdayan');
insert into address (street, postal_code, city) values ('5044 Gina Park', null, 'Pozhang');
insert into address (street, postal_code, city) values ('455 Del Sol Hill', null, 'Orahovica Donja');
insert into address (street, postal_code, city) values ('55 Jenifer Drive', 'F31', 'Swinford');
insert into address (street, postal_code, city) values ('337 Waywood Way', '1906', 'Frederiksberg');
insert into address (street, postal_code, city) values ('469 Sugar Drive', null, 'Sơn Hà');
insert into address (street, postal_code, city) values ('15 Dovetail Park', null, 'Karangintan');
insert into address (street, postal_code, city) values ('6622 Melvin Parkway', null, 'Dongjiao');
insert into address (street, postal_code, city) values ('82924 Elmside Crossing', null, 'Nikki');
insert into address (street, postal_code, city) values ('03 Rockefeller Hill', null, 'Mosfilotí');
insert into address (street, postal_code, city) values ('144 Sloan Drive', '51218', 'Podhum');
insert into address (street, postal_code, city) values ('9372 Oneill Hill', '8416', 'Socorro');
insert into address (street, postal_code, city) values ('8564 Duke Alley', '42082', 'La Palma');
insert into address (street, postal_code, city) values ('07124 Butterfield Place', null, 'Tanjung');
insert into address (street, postal_code, city) values ('99 Lakewood Gardens Avenue', '64525-000', 'Várzea Grande');
insert into address (street, postal_code, city) values ('79 Fairview Circle', null, 'Quţūr');
insert into address (street, postal_code, city) values ('6 Emmet Way', null, 'Zhangdiyingzi');
insert into address (street, postal_code, city) values ('0094 Eagan Road', null, 'Hongqi');
insert into address (street, postal_code, city) values ('339 Springview Pass', '33070 CEDEX', 'Bordeaux');
insert into address (street, postal_code, city) values ('9 Vera Park', '667999', 'Kyzyl');
insert into address (street, postal_code, city) values ('513 Veith Road', null, 'Vani');
insert into address (street, postal_code, city) values ('6140 Crowley Alley', null, 'Mbomba');
insert into address (street, postal_code, city) values ('4613 Corben Parkway', null, 'Gongdao');
insert into address (street, postal_code, city) values ('55216 Maple Wood Circle', '5501', 'Nagiba');
insert into address (street, postal_code, city) values ('26206 Moland Pass', '50933', 'Kuala Lumpur');
insert into address (street, postal_code, city) values ('8447 Dovetail Park', null, 'Cengang');
insert into address (street, postal_code, city) values ('72824 Waubesa Point', '8701', 'Sumilao');
insert into address (street, postal_code, city) values ('55 Washington Trail', null, 'Huajie');
insert into address (street, postal_code, city) values ('5449 Pond Lane', null, 'Dehang');
insert into address (street, postal_code, city) values ('702 Little Fleur Alley', '60306', 'Ciudad Cortés');
insert into address (street, postal_code, city) values ('5 Carpenter Plaza', null, 'Chipata');
insert into address (street, postal_code, city) values ('10 Old Gate Junction', '6008', 'Lugo');
insert into address (street, postal_code, city) values ('22 Prairieview Alley', '824 26', 'Hudiksvall');
insert into address (street, postal_code, city) values ('33 Colorado Court', '7209', 'Bagong Barrio');
insert into address (street, postal_code, city) values ('63 Union Crossing', null, 'Yankou');
insert into address (street, postal_code, city) values ('919 Northfield Crossing', '98800-000', 'Santo Ângelo');
insert into address (street, postal_code, city) values ('7184 3rd Parkway', '75413 CEDEX 08', 'Paris 08');
insert into address (street, postal_code, city) values ('50144 Petterle Drive', '94631 CEDEX 1', 'Rungis');
insert into address (street, postal_code, city) values ('40 Springview Street', '78204 CEDEX', 'Mantes-la-Jolie');
insert into address (street, postal_code, city) values ('4 Becker Crossing', '6419', 'San Vicente');
insert into address (street, postal_code, city) values ('315 Continental Park', '86001', 'Kelmė');
insert into address (street, postal_code, city) values ('965 Mayer Alley', null, 'Weekombaka');
insert into address (street, postal_code, city) values ('9 Delladonna Trail', '238323', 'Beloostrov');
insert into address (street, postal_code, city) values ('6 Pepper Wood Parkway', '91275', 'Rancho Nuevo');
insert into address (street, postal_code, city) values ('211 Ilene Place', null, 'Ichupampa');
insert into address (street, postal_code, city) values ('88913 Lakewood Gardens Hill', '58181', 'Khānewāl');
insert into address (street, postal_code, city) values ('742 Lillian Road', 'D6W', 'Dundrum');
insert into address (street, postal_code, city) values ('7 Ridgeview Place', 'MD-4734', 'Edineţ');
insert into address (street, postal_code, city) values ('79410 Carberry Crossing', '6527', 'Jaro');
insert into address (street, postal_code, city) values ('28188 Prairieview Park', '20160', 'Phan Thong');
insert into address (street, postal_code, city) values ('5 Messerschmidt Pass', '135 34', 'Tyresö');
insert into address (street, postal_code, city) values ('53862 Golf Course Way', null, 'Kuangyuan');
insert into address (street, postal_code, city) values ('411 Stone Corner Parkway', '11203', 'Gaspar Hernández');
insert into address (street, postal_code, city) values ('2 Riverside Road', '1228', 'Желино');
insert into address (street, postal_code, city) values ('0702 Mayfield Pass', null, 'Sharga');
insert into address (street, postal_code, city) values ('11 Union Road', '735538', 'San Antonio');
insert into address (street, postal_code, city) values ('85 Fairfield Trail', null, 'Banyubang');
insert into address (street, postal_code, city) values ('57836 Park Meadow Plaza', null, 'Maguwon');
insert into address (street, postal_code, city) values ('850 Packers Hill', null, 'Samur');
insert into address (street, postal_code, city) values ('02408 Anzinger Point', null, 'Tahilt');
insert into address (street, postal_code, city) values ('977 Heath Point', null, 'Gagarawa');
insert into address (street, postal_code, city) values ('00498 Killdeer Court', '13592 CEDEX 3', 'Aix-en-Provence');
insert into address (street, postal_code, city) values ('74 Loomis Terrace', '19001', 'Širvintos');
insert into address (street, postal_code, city) values ('1 Rigney Hill', null, 'Ouahigouya');
insert into address (street, postal_code, city) values ('50339 Myrtle Point', null, 'Campraksanta');
insert into address (street, postal_code, city) values ('7247 Ohio Street', '369264', 'Pregradnaya');
insert into address (street, postal_code, city) values ('34 Mccormick Pass', '141707', 'Novokhovrino');
insert into address (street, postal_code, city) values ('24 Kim Avenue', null, 'Runjin');
insert into address (street, postal_code, city) values ('4 Dayton Road', null, 'Peuteuy');
insert into address (street, postal_code, city) values ('3 Monica Street', null, 'Jangheung');
insert into address (street, postal_code, city) values ('74834 Hoepker Road', null, 'Cikaras');
insert into address (street, postal_code, city) values ('0 Bartillon Alley', '20167', 'Sterling');
insert into address (street, postal_code, city) values ('26056 Nelson Center', null, 'Shahre Jadide Andisheh');
insert into address (street, postal_code, city) values ('462 Moulton Drive', '05-170', 'Zakroczym');
insert into address (street, postal_code, city) values ('472 Mallory Street', null, 'Tlogowungu');
insert into address (street, postal_code, city) values ('73177 Moland Court', null, 'Pérama');
insert into address (street, postal_code, city) values ('216 Donald Alley', null, 'Wotsogo');
insert into address (street, postal_code, city) values ('24 Browning Court', null, 'Camp Diable');
insert into address (street, postal_code, city) values ('20 Hagan Plaza', '273 06', 'Libušín');
insert into address (street, postal_code, city) values ('4561 Burning Wood Avenue', null, 'Cibodas');
insert into address (street, postal_code, city) values ('56 Red Cloud Alley', '44273', 'Greda');
insert into address (street, postal_code, city) values ('49897 Kensington Place', '10702', 'San Cristóbal');
insert into address (street, postal_code, city) values ('78 Forest Dale Pass', '26100-000', 'Belford Roxo');
insert into address (street, postal_code, city) values ('716 Daystar Drive', null, 'Kallithéa');
insert into address (street, postal_code, city) values ('49024 Atwood Junction', '184433', 'Zapolyarnyy');
insert into address (street, postal_code, city) values ('3 Shopko Crossing', '692659', 'Novoshakhtinskiy');
insert into address (street, postal_code, city) values ('24 Vera Road', null, 'Aksu');
insert into address (street, postal_code, city) values ('28746 Kim Crossing', '48232', 'Detroit');
insert into address (street, postal_code, city) values ('31 Onsgard Avenue', '1964', 'Heemskerk');
insert into address (street, postal_code, city) values ('30928 Londonderry Parkway', null, 'Mafang');
insert into address (street, postal_code, city) values ('9 Chinook Avenue', null, 'Anyu');
insert into address (street, postal_code, city) values ('2268 Stuart Street', null, 'Wŏnsan');
insert into address (street, postal_code, city) values ('69 Corscot Junction', null, 'Masis');
insert into address (street, postal_code, city) values ('543 Melvin Way', '80668', 'Johor Bahru');
insert into address (street, postal_code, city) values ('3 Stoughton Alley', null, 'Limit');
insert into address (street, postal_code, city) values ('882 Claremont Court', '4765-122', 'Novais');
insert into address (street, postal_code, city) values ('5 Butterfield Way', null, 'Lukolela');
insert into address (street, postal_code, city) values ('184 Westerfield Drive', '85109 CEDEX', 'Les Sables-d''Olonne');
insert into address (street, postal_code, city) values ('0 Morrow Terrace', null, 'Malie');
insert into address (street, postal_code, city) values ('786 Shopko Pass', 'F52', 'Ballymahon');
insert into address (street, postal_code, city) values ('5071 Nova Avenue', null, 'Lowotukan');
insert into address (street, postal_code, city) values ('053 Brentwood Parkway', null, 'Gandu');
insert into address (street, postal_code, city) values ('4 Vahlen Place', '196627', 'Pavlovsk');
insert into address (street, postal_code, city) values ('1622 Westport Street', '98800', 'Nouméa');
insert into address (street, postal_code, city) values ('098 Gateway Street', '7010', 'Tongouson');
insert into address (street, postal_code, city) values ('8 Fulton Plaza', null, 'Mene de Mauroa');
insert into address (street, postal_code, city) values ('8291 Hagan Drive', '76105-000', 'Firminópolis');
insert into address (street, postal_code, city) values ('144 Iowa Circle', null, 'Xinglong');
insert into address (street, postal_code, city) values ('847 Havey Terrace', '2730-017', 'Tercena');
insert into address (street, postal_code, city) values ('83726 Cardinal Junction', '10184', 'New York City');
insert into address (street, postal_code, city) values ('02 Riverside Plaza', '42604 CEDEX', 'Montbrison');
insert into address (street, postal_code, city) values ('23237 Kensington Parkway', null, 'Ankazobe');
insert into address (street, postal_code, city) values ('634 2nd Road', null, 'Lávara');
insert into address (street, postal_code, city) values ('793 Crownhardt Hill', null, 'Hongtu');
insert into address (street, postal_code, city) values ('8 Huxley Drive', '252 31', 'Všenory');
insert into address (street, postal_code, city) values ('4994 Bashford Pass', null, 'Nacaome');
insert into address (street, postal_code, city) values ('58394 Hintze Park', '648-0002', 'Gojō');
insert into address (street, postal_code, city) values ('155 Montana Lane', null, 'Mlandizi');
insert into address (street, postal_code, city) values ('4352 Kenwood Terrace', '44004 CEDEX 1', 'Nantes');
insert into address (street, postal_code, city) values ('29475 Weeping Birch Alley', null, 'Vidoši');
insert into address (street, postal_code, city) values ('9041 Karstens Drive', '951017', 'El Retorno');
insert into address (street, postal_code, city) values ('2 Bluejay Pass', null, 'Datong');
insert into address (street, postal_code, city) values ('9 Weeping Birch Parkway', '299-0271', 'Kisarazu');
insert into address (street, postal_code, city) values ('9 Charing Cross Crossing', null, 'Kezileboyi');
insert into address (street, postal_code, city) values ('340 Clemons Way', null, 'Ngurore');
insert into address (street, postal_code, city) values ('49 Bay Trail', null, 'Ambarita');
insert into address (street, postal_code, city) values ('5 Novick Court', '1693', 'Tembisa');
insert into address (street, postal_code, city) values ('9185 Schmedeman Point', null, 'Thị Trấn Ngải Giao');
insert into address (street, postal_code, city) values ('0876 Gina Terrace', null, 'Pajeksan');
insert into address (street, postal_code, city) values ('9839 Westport Hill', null, 'Macapo');
insert into address (street, postal_code, city) values ('15 Cambridge Parkway', null, 'Kananga');
insert into address (street, postal_code, city) values ('07344 Fieldstone Lane', null, 'Lamalewo');
insert into address (street, postal_code, city) values ('1499 Surrey Junction', '46825-000', 'Igarapé Miri');
insert into address (street, postal_code, city) values ('462 Clarendon Terrace', '48-250', 'Głogówek');
insert into address (street, postal_code, city) values ('8 Farragut Hill', null, 'Ţayyibat al Imām');
insert into address (street, postal_code, city) values ('10 5th Junction', null, 'Sanxixiang');
insert into address (street, postal_code, city) values ('6540 Nevada Road', '8029', 'Bodø');
insert into address (street, postal_code, city) values ('395 Dottie Alley', '75434 CEDEX 09', 'Paris 09');
insert into address (street, postal_code, city) values ('96245 Mallard Pass', null, 'Asadābād');
insert into address (street, postal_code, city) values ('19355 Lighthouse Bay Way', null, 'Kanada');
insert into address (street, postal_code, city) values ('88 Daystar Center', null, 'Xarardheere');
insert into address (street, postal_code, city) values ('51 Schurz Crossing', '97019 CEDEX', 'Pointe-à-Pitre');
insert into address (street, postal_code, city) values ('08717 Ryan Trail', '13200-000', 'Jundiaí');
insert into address (street, postal_code, city) values ('9321 Fordem Circle', null, 'Jombang');
insert into address (street, postal_code, city) values ('0730 Johnson Place', '416067', 'La Plata');
insert into address (street, postal_code, city) values ('22246 Armistice Street', '31-827', 'Dzików Stary');
insert into address (street, postal_code, city) values ('42227 Buena Vista Street', null, 'Chenzhou');
insert into address (street, postal_code, city) values ('4 Porter Pass', null, 'Bayanbaraat');
insert into address (street, postal_code, city) values ('89286 Raven Point', '5571', 'Levin');
insert into address (street, postal_code, city) values ('721 Dexter Parkway', '4212', 'Katuli');
insert into address (street, postal_code, city) values ('0637 Lien Lane', '24053 CEDEX', 'Périgueux');
insert into address (street, postal_code, city) values ('32 Vernon Park', '22130', 'Laem Sing');
insert into address (street, postal_code, city) values ('296 Bashford Crossing', '646860', 'Odesskoye');
insert into address (street, postal_code, city) values ('59859 Spohn Circle', null, 'Khūgyāṉī');
insert into address (street, postal_code, city) values ('9 Everett Road', null, 'Sangmu');
insert into address (street, postal_code, city) values ('31 Mallard Court', null, 'Gewanē');
insert into address (street, postal_code, city) values ('31 Blackbird Park', 'A86', 'Confey');
insert into address (street, postal_code, city) values ('59 Columbus Way', '84105', 'Salt Lake City');
insert into address (street, postal_code, city) values ('4 Lakewood Junction', null, 'Verkhniy Rohachyk');
insert into address (street, postal_code, city) values ('0 Center Street', '27700-000', 'Vassouras');
insert into address (street, postal_code, city) values ('15533 Melody Junction', null, 'Ibarra');
insert into address (street, postal_code, city) values ('90525 Ludington Point', '4713', 'Abaca');
insert into address (street, postal_code, city) values ('1 Bobwhite Place', null, 'Huaccana');
insert into address (street, postal_code, city) values ('8032 Waxwing Place', '1002', 'Da-an Sur');
insert into address (street, postal_code, city) values ('56861 Cascade Circle', null, 'Huayang');
insert into address (street, postal_code, city) values ('7 Lien Court', '139 51', 'Värmdö');
insert into address (street, postal_code, city) values ('47 Farwell Terrace', '1104', 'Sionogan');
insert into address (street, postal_code, city) values ('412 Judy Avenue', null, 'Barubandung');
insert into address (street, postal_code, city) values ('33 Macpherson Way', '2402', 'Labrador');
insert into address (street, postal_code, city) values ('02 Kinsman Alley', null, 'Mawang');
insert into address (street, postal_code, city) values ('15 Lotheville Hill', '453019', 'Akademgorodok');
insert into address (street, postal_code, city) values ('420 Esch Drive', '2317', 'Blinsung');
insert into address (street, postal_code, city) values ('6 Sugar Street', null, 'Novoselë');
insert into address (street, postal_code, city) values ('50 Shelley Avenue', null, 'Nanying');
insert into address (street, postal_code, city) values ('899 Hagan Center', null, 'Chixi');
insert into address (street, postal_code, city) values ('5 Vernon Center', null, 'Settat');
insert into address (street, postal_code, city) values ('693 Bluejay Center', '21140', 'Ban Nong Wua So');
insert into address (street, postal_code, city) values ('324 Manitowish Point', '37250-000', 'Nepomuceno');
insert into address (street, postal_code, city) values ('4 Moulton Center', null, 'Jiantou');
insert into address (street, postal_code, city) values ('79 Bay Court', '27180', 'Bueng Sam Phan');
insert into address (street, postal_code, city) values ('39 Ridgeway Lane', '5060-569', 'Torre do Pinhão');
insert into address (street, postal_code, city) values ('2 Rutledge Drive', '30001', 'Karaundi');
insert into address (street, postal_code, city) values ('8534 Scofield Center', null, 'Olleros');
insert into address (street, postal_code, city) values ('3783 Hoffman Way', null, 'Taman');
insert into address (street, postal_code, city) values ('47 Esker Way', null, 'Nam Sách');
insert into address (street, postal_code, city) values ('0634 Elgar Park', '661008', 'Dos Quebradas');
insert into address (street, postal_code, city) values ('09640 Glendale Parkway', null, 'Dalongzhan');
insert into address (street, postal_code, city) values ('48838 Dexter Point', null, 'Darband');
insert into address (street, postal_code, city) values ('28617 Lyons Hill', '984-0075', 'Sendai-shi');
insert into address (street, postal_code, city) values ('9 Cottonwood Hill', '30502', 'La Suiza');
insert into address (street, postal_code, city) values ('219 Forest Terrace', null, 'Weizheng');
insert into address (street, postal_code, city) values ('631 Briar Crest Lane', '4223', 'Stamboliyski');
insert into address (street, postal_code, city) values ('98 Morningstar Hill', null, 'Palaihari');
insert into address (street, postal_code, city) values ('6 Golden Leaf Point', '94723', 'Petrolera');
insert into address (street, postal_code, city) values ('2 Center Court', null, 'Haradzishcha');
insert into address (street, postal_code, city) values ('772 Melby Park', null, 'Shanjiang');
insert into address (street, postal_code, city) values ('5 Longview Lane', null, 'Qianxu Zhen');
insert into address (street, postal_code, city) values ('1838 Blackbird Crossing', null, 'Nuga');
insert into address (street, postal_code, city) values ('6 Anhalt Hill', '6304', 'Lila');
insert into address (street, postal_code, city) values ('482 Continental Terrace', '76129', 'Fort Worth');
insert into address (street, postal_code, city) values ('7 Bunting Terrace', '55160', 'Ongkharak');
insert into address (street, postal_code, city) values ('62298 Coolidge Court', null, 'Bantardawa');
insert into address (street, postal_code, city) values ('67 Gulseth Crossing', null, 'Labrang');
insert into address (street, postal_code, city) values ('37 Shoshone Center', '20960', 'Turku');
insert into address (street, postal_code, city) values ('6 Meadow Valley Pass', '8600', 'Yambol');
insert into address (street, postal_code, city) values ('98957 Grover Parkway', '21037', 'Hamburg');
insert into address (street, postal_code, city) values ('15 Hoepker Parkway', null, 'Yangxi');
insert into address (street, postal_code, city) values ('87 Graedel Park', null, 'Noebesa');
insert into address (street, postal_code, city) values ('9736 Hallows Road', null, 'Tancheng');
insert into address (street, postal_code, city) values ('338 Farwell Circle', '49200-000', 'Estância');
insert into address (street, postal_code, city) values ('4 Lakeland Road', '48324', 'Santa Maria');
insert into address (street, postal_code, city) values ('75062 Moulton Lane', null, 'Padangtepung');
insert into address (street, postal_code, city) values ('166 Bluejay Road', '353210', 'Novotitarovskaya');
insert into address (street, postal_code, city) values ('4 Donald Drive', '142817', 'Zyuzino');
insert into address (street, postal_code, city) values ('0601 Forest Parkway', '3064', 'Bandera');
insert into address (street, postal_code, city) values ('20 Northwestern Street', null, 'Chixi');
insert into address (street, postal_code, city) values ('92 Dennis Hill', '413 26', 'Göteborg');
insert into address (street, postal_code, city) values ('1957 High Crossing Pass', '17250-000', 'Bariri');
insert into address (street, postal_code, city) values ('617 Gateway Circle', '963-8878', 'Kōriyama');
insert into address (street, postal_code, city) values ('702 Lyons Point', '686 91', 'Sunne');
insert into address (street, postal_code, city) values ('11149 Crest Line Road', null, 'Dashu');
insert into address (street, postal_code, city) values ('88 Starling Pass', '37554 CEDEX', 'Saint-Avertin');
insert into address (street, postal_code, city) values ('78 Autumn Leaf Drive', '28944', 'Fuenlabrada');
insert into address (street, postal_code, city) values ('46450 Linden Street', '64103', 'San Isidro');
insert into address (street, postal_code, city) values ('44 Stephen Center', '35215', 'Birmingham');
insert into address (street, postal_code, city) values ('332 Victoria Pass', null, 'Gunungpeundeuy');
insert into address (street, postal_code, city) values ('79 Lunder Junction', null, 'Kowo');
insert into address (street, postal_code, city) values ('4886 Main Park', null, 'Hyesan-dong');
insert into address (street, postal_code, city) values ('30043 Ludington Street', '923 98', 'Storuman');
insert into address (street, postal_code, city) values ('2664 Elgar Pass', '88780-000', 'Imbituba');
insert into address (street, postal_code, city) values ('011 Mitchell Lane', '3009', 'Rotterdam postbusnummers');
insert into address (street, postal_code, city) values ('90 Union Trail', '28114 CEDEX', 'Lucé');
insert into address (street, postal_code, city) values ('17 Merrick Avenue', '7045', 'Nelson');
insert into address (street, postal_code, city) values ('44 Shasta Pass', null, 'Taohuajiang');
insert into address (street, postal_code, city) values ('43233 Anderson Junction', '463 03', 'Stráž nad Nisou');
insert into address (street, postal_code, city) values ('8857 Forster Alley', null, 'Huaqiao');
insert into address (street, postal_code, city) values ('4537 Luster Plaza', '40160', 'Mancha Khiri');
insert into address (street, postal_code, city) values ('503 Goodland Circle', null, 'Sok Kwu Wan');
insert into address (street, postal_code, city) values ('26 Dapin Road', '2826', 'Motrico');
insert into address (street, postal_code, city) values ('63 Shelley Junction', null, 'Judita');
insert into address (street, postal_code, city) values ('133 Briar Crest Alley', null, 'Lincheng');
insert into address (street, postal_code, city) values ('897 Clyde Gallagher Avenue', null, 'Luzhou');
insert into address (street, postal_code, city) values ('8 Doe Crossing Point', null, 'Yangjiafang');
insert into address (street, postal_code, city) values ('3 Fuller Pass', '37032 CEDEX 1', 'Tours');
insert into address (street, postal_code, city) values ('44113 Del Sol Alley', null, 'Bolekhiv');
insert into address (street, postal_code, city) values ('9314 Union Alley', '78220', 'San Antonio');
insert into address (street, postal_code, city) values ('4 Butterfield Park', null, 'Hoçisht');
insert into address (street, postal_code, city) values ('728 Helena Lane', null, 'Timeng');
insert into address (street, postal_code, city) values ('920 Express Park', null, 'Mashan');
insert into address (street, postal_code, city) values ('78 Crownhardt Street', '789 71', 'Leština');
insert into address (street, postal_code, city) values ('3 3rd Alley', null, 'Njeru');
insert into address (street, postal_code, city) values ('20265 Novick Circle', '90094', 'Los Angeles');
insert into address (street, postal_code, city) values ('83729 Magdeline Point', null, 'Sukawening');
insert into address (street, postal_code, city) values ('15 Red Cloud Point', null, 'Langue');
insert into address (street, postal_code, city) values ('28 Vidon Drive', null, 'Ar Ruḩaybah');
insert into address (street, postal_code, city) values ('0370 Quincy Court', '77-141', 'Borzytuchom');
insert into address (street, postal_code, city) values ('88 Bellgrove Lane', '601430', 'Vyazniki');
insert into address (street, postal_code, city) values ('129 Sunfield Alley', '30853', 'Francisco I Madero');
insert into address (street, postal_code, city) values ('92943 Fair Oaks Pass', null, 'Tegaldowo');
insert into address (street, postal_code, city) values ('038 Pennsylvania Court', null, 'Gesing');
insert into address (street, postal_code, city) values ('371 Dawn Crossing', '053817', 'Concepción');
insert into address (street, postal_code, city) values ('2 Hagan Plaza', null, 'Yangsa');
insert into address (street, postal_code, city) values ('6597 Ridgeway Drive', null, 'Kyenjojo');
insert into address (street, postal_code, city) values ('34570 Mitchell Hill', null, 'Shuinan');
insert into address (street, postal_code, city) values ('791 Eliot Park', '361327', 'Staryy Cherek');
insert into address (street, postal_code, city) values ('101 Cambridge Drive', null, 'Zghartā');
insert into address (street, postal_code, city) values ('4 Warbler Way', null, 'Gostovići');
insert into address (street, postal_code, city) values ('21 Scott Point', null, 'El Copé');
insert into address (street, postal_code, city) values ('81 Amoth Point', 'MD-3300', 'Tiraspol');
insert into address (street, postal_code, city) values ('263 Sloan Circle', null, 'Noeltoko');
insert into address (street, postal_code, city) values ('028 Ronald Regan Way', null, 'Gaoshi');
insert into address (street, postal_code, city) values ('03378 Washington Pass', '9607', 'Damatulan');
insert into address (street, postal_code, city) values ('69 Sage Pass', '27040', 'Tierra y Libertad');
insert into address (street, postal_code, city) values ('3 Ridgeview Park', null, 'Hanghuadian');
insert into address (street, postal_code, city) values ('61310 Tony Junction', '58900-000', 'Cajazeiras');
insert into address (street, postal_code, city) values ('0 Little Fleur Place', null, 'Varazqān');
insert into address (street, postal_code, city) values ('3637 Darwin Plaza', '1241', 'Moste');
insert into address (street, postal_code, city) values ('4 Steensland Crossing', null, 'Las Lajas');
insert into address (street, postal_code, city) values ('553 Killdeer Avenue', '68500-000', 'Marabá');
insert into address (street, postal_code, city) values ('450 Scott Street', null, 'Tiebiancheng');
insert into address (street, postal_code, city) values ('51390 Main Alley', '9600-213', 'Ribeira Seca');
insert into address (street, postal_code, city) values ('46 Carey Trail', '47-420', 'Kuźnia Raciborska');
insert into address (street, postal_code, city) values ('232 Goodland Trail', '3025-543', 'São Silvestre');
insert into address (street, postal_code, city) values ('03 Prairie Rose Drive', null, 'Neochóri');
insert into address (street, postal_code, city) values ('315 Straubel Avenue', null, 'Hot');
insert into address (street, postal_code, city) values ('728 Riverside Road', '178057', 'Riosucio');
insert into address (street, postal_code, city) values ('74991 Calypso Lane', null, '‘Izbat al Burj');
insert into address (street, postal_code, city) values ('70059 South Trail', null, 'Muraharjo');
insert into address (street, postal_code, city) values ('1 Columbus Pass', null, 'Jitan');
insert into address (street, postal_code, city) values ('50 Hermina Road', null, 'Pamarayan');
insert into address (street, postal_code, city) values ('37 Barby Plaza', '988-0505', 'Minato');
insert into address (street, postal_code, city) values ('1 Pine View Center', '9500', 'Buayan');
insert into address (street, postal_code, city) values ('0 Roth Road', '57509 CEDEX', 'Saint-Avold');
insert into address (street, postal_code, city) values ('1455 Kings Trail', '22200', 'Nuwara Eliya');
insert into address (street, postal_code, city) values ('93756 Shelley Court', null, 'Sājir');
insert into address (street, postal_code, city) values ('0 Crowley Lane', null, 'Tanrake Village');
insert into address (street, postal_code, city) values ('17 Amoth Drive', null, 'Terpsithéa');
insert into address (street, postal_code, city) values ('54869 Bayside Court', null, 'Zhongfan');
insert into address (street, postal_code, city) values ('696 Grover Point', null, 'Isiolo');
insert into address (street, postal_code, city) values ('551 Pleasure Junction', null, 'Xizhong');
insert into address (street, postal_code, city) values ('72 Ohio Pass', null, 'Kisasa');
insert into address (street, postal_code, city) values ('0 Morning Crossing', '49003', 'Zamora');
insert into address (street, postal_code, city) values ('0322 Washington Street', null, 'Uga');
insert into address (street, postal_code, city) values ('06789 Rockefeller Circle', null, 'Heihe');
insert into address (street, postal_code, city) values ('734 Sullivan Hill', null, 'San Juan Pueblo');
insert into address (street, postal_code, city) values ('56 Steensland Trail', '386250', 'Nesterovskaya');
insert into address (street, postal_code, city) values ('830 Buhler Point', '7011', 'Bayog');
insert into address (street, postal_code, city) values ('8 Westerfield Crossing', null, 'Orlu');
insert into address (street, postal_code, city) values ('139 Mosinee Drive', '66140', 'Sam Ngam');
insert into address (street, postal_code, city) values ('14 Lyons Park', '330 16', 'Všeruby');
insert into address (street, postal_code, city) values ('0884 Randy Road', null, 'Kulutan');
insert into address (street, postal_code, city) values ('490 Bultman Trail', '48040', 'San Agustin');
insert into address (street, postal_code, city) values ('7077 Hintze Circle', '5117', 'San Jorge');
insert into address (street, postal_code, city) values ('736 Rieder Drive', null, 'Gujiang');
insert into address (street, postal_code, city) values ('32 6th Trail', null, 'Taunoa');
insert into address (street, postal_code, city) values ('6 Toban Way', null, 'Zharrëz');
insert into address (street, postal_code, city) values ('704 Farragut Road', '747 44', 'Březová');
insert into address (street, postal_code, city) values ('7098 Artisan Alley', null, 'Road Town');
insert into address (street, postal_code, city) values ('297 Carpenter Street', '668110', 'Chadan');
insert into address (street, postal_code, city) values ('4 Rieder Hill', '7102', 'Roxas');
insert into address (street, postal_code, city) values ('34280 Lukken Road', null, 'Sidonganti');
insert into address (street, postal_code, city) values ('063 Memorial Park', '87-522', 'Ostrowite');
insert into address (street, postal_code, city) values ('78 Westport Hill', null, 'Shifang');
insert into address (street, postal_code, city) values ('51 Sunbrook Parkway', null, 'Klenovyy');
insert into address (street, postal_code, city) values ('271 Mayer Hill', '368160', 'Zandak');
insert into address (street, postal_code, city) values ('8 Kenwood Way', '187327', 'Sinyavino');
insert into address (street, postal_code, city) values ('782 Annamark Lane', '45075 CEDEX 2', 'Orléans');
insert into address (street, postal_code, city) values ('83 International Way', '21490', 'Marttila');
insert into address (street, postal_code, city) values ('87715 Dunning Road', null, 'Shadui');
insert into address (street, postal_code, city) values ('9 Bonner Crossing', '4820-009', 'Fafe');
insert into address (street, postal_code, city) values ('7 Thierer Lane', null, 'Jiahe');
insert into address (street, postal_code, city) values ('292 Marcy Plaza', '1333', 'Крива Паланка');
insert into address (street, postal_code, city) values ('102 Dottie Lane', '34-322', 'Gilowice');
insert into address (street, postal_code, city) values ('879 Homewood Pass', null, 'Cikuya');
insert into address (street, postal_code, city) values ('29 Tennyson Pass', '3230', 'Sandefjord');
insert into address (street, postal_code, city) values ('98 Nova Avenue', null, 'Tuopu');
insert into address (street, postal_code, city) values ('41363 Grasskamp Place', null, 'Liufu');
insert into address (street, postal_code, city) values ('20 Hayes Place', '63-510', 'Mikstat');
insert into address (street, postal_code, city) values ('24693 Kropf Trail', '475038', 'Plato');
insert into address (street, postal_code, city) values ('920 Burrows Drive', '5212', 'Avellaneda');
insert into address (street, postal_code, city) values ('79335 Iowa Point', null, 'Lanxi');
insert into address (street, postal_code, city) values ('9 Pawling Center', null, 'Palama');
insert into address (street, postal_code, city) values ('43624 Elgar Hill', null, 'Shuidong');
insert into address (street, postal_code, city) values ('15316 Center Plaza', null, 'Liuji');
insert into address (street, postal_code, city) values ('68674 Arkansas Road', null, 'Al Manşūrah');
insert into address (street, postal_code, city) values ('58921 Hayes Hill', null, 'Cigembong');
insert into address (street, postal_code, city) values ('09 Springview Hill', null, 'Zekou');
insert into address (street, postal_code, city) values ('0749 2nd Way', null, 'Dagang');
insert into address (street, postal_code, city) values ('98 Monterey Junction', '8601', 'Matabao');
insert into address (street, postal_code, city) values ('28 Everett Lane', null, 'Xinying');
insert into address (street, postal_code, city) values ('809 Shelley Hill', null, 'Zengjia');
insert into address (street, postal_code, city) values ('9170 Johnson Hill', '28914', 'Leganes');
insert into address (street, postal_code, city) values ('306 Tony Alley', null, 'Shiling');
insert into address (street, postal_code, city) values ('626 Hoard Junction', null, 'Rožaje');
insert into address (street, postal_code, city) values ('04332 Pierstorff Point', '134548', 'Morales');
insert into address (street, postal_code, city) values ('21308 South Terrace', '68-219', 'Tuplice');
insert into address (street, postal_code, city) values ('9816 John Wall Drive', '2435-585', 'Peras Ruivas');
insert into address (street, postal_code, city) values ('084 Muir Place', '32-765', 'Krzeczów');
insert into address (street, postal_code, city) values ('0472 Bunting Pass', '9265', 'Černelavci');
insert into address (street, postal_code, city) values ('175 Cardinal Circle', null, 'Lamakera Dua');
insert into address (street, postal_code, city) values ('384 Blaine Point', null, 'Yangdang');
insert into address (street, postal_code, city) values ('5 Mayer Plaza', '82-340', 'Tolkmicko');
insert into address (street, postal_code, city) values ('09917 Vera Road', null, 'Udi');
insert into address (street, postal_code, city) values ('937 Scofield Terrace', null, 'Prokuplje');
insert into address (street, postal_code, city) values ('86987 Golden Leaf Hill', '44-186', 'Gierałtowice');
insert into address (street, postal_code, city) values ('86265 Dexter Pass', '60550', 'Nurmo');
insert into address (street, postal_code, city) values ('869 Killdeer Place', '30001', 'Bhakkar');
insert into address (street, postal_code, city) values ('9575 South Drive', '184366', 'Baykalovo');
insert into address (street, postal_code, city) values ('10892 Chive Drive', '34-472', 'Piekielnik');
insert into address (street, postal_code, city) values ('301 Pawling Road', null, 'Xinmen');
insert into address (street, postal_code, city) values ('6486 Shasta Way', null, 'Finiq');
insert into address (street, postal_code, city) values ('58 Novick Hill', '7000', 'Ruse');
insert into address (street, postal_code, city) values ('7537 Esker Drive', null, 'Anning');
insert into address (street, postal_code, city) values ('9829 Algoma Way', null, 'Xuebu');
insert into address (street, postal_code, city) values ('172 Moulton Court', '35680-000', 'Itaúna');
insert into address (street, postal_code, city) values ('68923 Anderson Terrace', null, 'Xinbu');
insert into address (street, postal_code, city) values ('5423 Fairfield Plaza', null, 'Temanjang');
insert into address (street, postal_code, city) values ('874 Northridge Avenue', null, 'Paobulan');
insert into address (street, postal_code, city) values ('23 Sycamore Junction', '141143', 'Zagoryanskiy');
insert into address (street, postal_code, city) values ('5 Mcbride Pass', null, 'Shuiyuesi');
insert into address (street, postal_code, city) values ('91668 Packers Pass', null, 'Mushu');
insert into address (street, postal_code, city) values ('3 Eliot Street', null, 'Sitampiky');
insert into address (street, postal_code, city) values ('0120 New Castle Pass', null, 'Qingquan');
insert into address (street, postal_code, city) values ('3593 New Castle Drive', '2420-055', 'Caldelas');
insert into address (street, postal_code, city) values ('2174 Rusk Center', null, 'Pomabamba');
insert into address (street, postal_code, city) values ('9670 Eagan Terrace', null, 'Chengbei');
insert into address (street, postal_code, city) values ('690 Parkside Avenue', '360-0201', 'Menuma');
insert into address (street, postal_code, city) values ('89 Namekagon Drive', '45149', 'Essen');
insert into address (street, postal_code, city) values ('42400 Loomis Trail', '871 60', 'Härnösand');
insert into address (street, postal_code, city) values ('88 Portage Plaza', null, 'Athens');
insert into address (street, postal_code, city) values ('683 Roxbury Junction', null, 'Bulakbanjar');
insert into address (street, postal_code, city) values ('719 Hansons Crossing', null, 'Pelópion');
insert into address (street, postal_code, city) values ('6 Crowley Junction', 'D04', 'Cabinteely');
insert into address (street, postal_code, city) values ('5811 Barby Alley', '84200-000', 'Jaguariaíva');
insert into address (street, postal_code, city) values ('73036 Superior Circle', null, 'Camp Diable');
insert into address (street, postal_code, city) values ('7913 Arrowood Hill', '238323', 'Beloostrov');
insert into address (street, postal_code, city) values ('54785 Burning Wood Plaza', '89136-000', 'Gavea');
insert into address (street, postal_code, city) values ('01 Carberry Plaza', '682038', 'Chegdomyn');
insert into address (street, postal_code, city) values ('0574 Butternut Road', null, 'Longar');
insert into address (street, postal_code, city) values ('388 Trailsway Hill', null, 'Bununu Kasa');
insert into address (street, postal_code, city) values ('53 La Follette Trail', '671950', 'Zakamensk');
insert into address (street, postal_code, city) values ('11403 Pankratz Terrace', '86-260', 'Unisław');
insert into address (street, postal_code, city) values ('09 Browning Avenue', '26-330', 'Żarnów');
insert into address (street, postal_code, city) values ('9221 Cordelia Lane', '76600', 'Le Havre');
insert into address (street, postal_code, city) values ('4 Talisman Way', '832 47', 'Frösön');
insert into address (street, postal_code, city) values ('1 Hintze Way', null, 'Simo Satu');
insert into address (street, postal_code, city) values ('365 Delladonna Center', null, 'Loncoche');
insert into address (street, postal_code, city) values ('14290 Hoard Center', null, 'Zhuge');
insert into address (street, postal_code, city) values ('50 Oriole Center', '4980-403', 'Bemposta');
insert into address (street, postal_code, city) values ('85409 Hanson Drive', '538 62', 'Hrochův Týnec');
insert into address (street, postal_code, city) values ('35819 Canary Road', '545 30', 'Töreboda');
insert into address (street, postal_code, city) values ('89 Hanson Circle', null, 'Lukolela');
insert into address (street, postal_code, city) values ('839 Prairieview Road', '861 24', 'Timrå');
insert into address (street, postal_code, city) values ('62 Bayside Street', '8023', 'Zürich');
insert into address (street, postal_code, city) values ('07 Northridge Pass', null, 'Urung');
insert into address (street, postal_code, city) values ('818 Westerfield Drive', null, 'Santa Cruz de Yojoa');
insert into address (street, postal_code, city) values ('0 Talmadge Hill', null, 'Hejiabao');
insert into address (street, postal_code, city) values ('6768 Maple Center', '2925-017', 'Aldeia da Piedade');
insert into address (street, postal_code, city) values ('0 Loomis Plaza', null, 'Iperu');
insert into address (street, postal_code, city) values ('92960 Manitowish Circle', '354 91', 'Lázně Kynžvart');
insert into address (street, postal_code, city) values ('39603 Ramsey Center', null, 'Lloqan');
insert into address (street, postal_code, city) values ('92 Oakridge Hill', '509-6251', 'Toki');
insert into address (street, postal_code, city) values ('8568 5th Hill', null, 'Kefar Shemaryahu');
insert into address (street, postal_code, city) values ('2 Forest Dale Drive', null, 'Stavyshche');
insert into address (street, postal_code, city) values ('89 Anzinger Circle', null, 'Chauk');
insert into address (street, postal_code, city) values ('95563 Bowman Hill', null, 'Carthage');
insert into address (street, postal_code, city) values ('8494 Pankratz Drive', null, 'Kalāleh');
insert into address (street, postal_code, city) values ('4051 Stuart Way', '818-0138', 'Dazaifu');
insert into address (street, postal_code, city) values ('1 Oak Trail', null, 'Khal’ch');
insert into address (street, postal_code, city) values ('625 Bay Alley', '3009', 'Rotterdam postbusnummers');
insert into address (street, postal_code, city) values ('2862 East Crossing', '3249', 'Sandefjord');
insert into address (street, postal_code, city) values ('0 Loeprich Court', '1275', 'Baculongan');
insert into address (street, postal_code, city) values ('05589 Mariners Cove Trail', '33064', 'Pompano Beach');
insert into address (street, postal_code, city) values ('440 Stephen Crossing', null, 'Liantan');
insert into address (street, postal_code, city) values ('9051 Fair Oaks Lane', null, 'Heping');
insert into address (street, postal_code, city) values ('9381 Dakota Way', null, 'Agios Dimitrios');
insert into address (street, postal_code, city) values ('2766 Delladonna Park', '30280', 'Songkhla');
insert into address (street, postal_code, city) values ('06 Eastlawn Parkway', '58-588', 'Cieplice Śląskie Zdrój');
insert into address (street, postal_code, city) values ('5784 Dawn Terrace', '694440', 'Rybinsk');
insert into address (street, postal_code, city) values ('842 Sommers Drive', '694820', 'Tomari');
insert into address (street, postal_code, city) values ('8047 North Parkway', '67110', 'Lom Sak');
insert into address (street, postal_code, city) values ('2056 Dottie Trail', null, 'Krajan');
insert into address (street, postal_code, city) values ('2 Hanover Street', '6330', 'Struga');
insert into address (street, postal_code, city) values ('33 Scofield Point', '2727', 'Pudoc North');
insert into address (street, postal_code, city) values ('6047 Vernon Junction', null, 'Karangmulyo');
insert into address (street, postal_code, city) values ('8138 Dryden Pass', null, 'Moyamba');
insert into address (street, postal_code, city) values ('570 Hallows Court', '69405-000', 'Iranduba');
insert into address (street, postal_code, city) values ('34 Golf Drive', '42001', 'Rokiškis');
insert into address (street, postal_code, city) values ('47644 Portage Lane', null, 'Tamianglayang');
insert into address (street, postal_code, city) values ('7 Bunting Alley', '249884', 'Maloyaroslavets');
insert into address (street, postal_code, city) values ('83 Russell Point', null, 'Hongqi');
insert into address (street, postal_code, city) values ('26 East Drive', '396026', 'Ramon’');
insert into address (street, postal_code, city) values ('4334 Continental Drive', null, 'Warungbanten');
insert into address (street, postal_code, city) values ('9797 Everett Plaza', null, 'Gaojimiao');
insert into address (street, postal_code, city) values ('6 Commercial Center', '238346', 'Волочаевское');
insert into address (street, postal_code, city) values ('7610 Muir Crossing', null, 'Taishan');
insert into address (street, postal_code, city) values ('25 Ohio Way', '357128', 'Nevinnomyssk');
insert into address (street, postal_code, city) values ('595 Steensland Park', '1707', 'København');
insert into address (street, postal_code, city) values ('078 Vidon Avenue', '7108', 'Sergio Osmeña Sr');
insert into address (street, postal_code, city) values ('62801 Autumn Leaf Parkway', null, 'Mesa');
insert into address (street, postal_code, city) values ('58 Hovde Parkway', '2765-366', 'Livramento');
insert into address (street, postal_code, city) values ('9 Kedzie Circle', '606488', 'Pamyat’ Parizhskoy Kommuny');
insert into address (street, postal_code, city) values ('77 Eagan Way', null, 'Jiangxi');
insert into address (street, postal_code, city) values ('1 7th Pass', '5046', 'Granada');
insert into address (street, postal_code, city) values ('665 Golf Course Drive', null, 'Leworook');
insert into address (street, postal_code, city) values ('419 Everett Way', '303211', 'Kromy');
insert into address (street, postal_code, city) values ('73 Superior Trail', null, 'Sukasada');
insert into address (street, postal_code, city) values ('79637 Nelson Trail', '46801', 'Petaling Jaya');
insert into address (street, postal_code, city) values ('4902 Lighthouse Bay Trail', null, 'Sun Kunda');
insert into address (street, postal_code, city) values ('560 Kingsford Road', null, 'Bangkle');
insert into address (street, postal_code, city) values ('42 Logan Way', '404172', 'Yeysk');
insert into address (street, postal_code, city) values ('80402 Swallow Court', '5307', 'Lapi');
insert into address (street, postal_code, city) values ('7 Merry Trail', '684527', 'Puente Nacional');
insert into address (street, postal_code, city) values ('3 Westend Circle', null, 'Tegina');
insert into address (street, postal_code, city) values ('72 Mallory Hill', '4765-405', 'Guardizela');
insert into address (street, postal_code, city) values ('5 Eastlawn Road', '39410', 'Broby');
insert into address (street, postal_code, city) values ('06556 Erie Terrace', '33619', 'Bielefeld');
insert into address (street, postal_code, city) values ('5 Dennis Plaza', 'M5E', 'Napanee Downtown');
insert into address (street, postal_code, city) values ('6911 Cascade Center', null, 'Yushugou');
insert into address (street, postal_code, city) values ('7 Fairview Alley', null, 'Shaba Zhen');
insert into address (street, postal_code, city) values ('9 Oakridge Street', '27040', 'Tierra y Libertad');
insert into address (street, postal_code, city) values ('18349 Dunning Center', '44110', 'Chaem Luang');
insert into address (street, postal_code, city) values ('58 Beilfuss Court', '3140-480', 'Portela');
insert into address (street, postal_code, city) values ('2 Rutledge Center', '890-0073', 'Usuki');
insert into address (street, postal_code, city) values ('300 Scoville Pass', '9302', 'Montilla');
insert into address (street, postal_code, city) values ('701 Kennedy Place', null, 'Tangzhuang');
insert into address (street, postal_code, city) values ('55 Mcguire Circle', '53000-000', 'Olinda');
insert into address (street, postal_code, city) values ('86 Donald Circle', null, 'Supu');
insert into address (street, postal_code, city) values ('10325 Warbler Point', null, 'Jintao');
insert into address (street, postal_code, city) values ('6 Mayer Drive', null, 'Agarsin');
insert into address (street, postal_code, city) values ('9216 Dawn Junction', 'L-6834', 'Biwer');
insert into address (street, postal_code, city) values ('1191 Bluejay Drive', null, 'Erdaohe');
insert into address (street, postal_code, city) values ('36799 Northfield Avenue', '4480-014', 'Arcos');
insert into address (street, postal_code, city) values ('33844 Longview Alley', null, 'Yongning');
insert into address (street, postal_code, city) values ('9417 Bowman Alley', null, 'Mariel');
insert into address (street, postal_code, city) values ('8 Springs Lane', null, 'Bazar-Korgon');
insert into address (street, postal_code, city) values ('963 Melby Trail', '9615', 'Buldon');
insert into address (street, postal_code, city) values ('8 Maryland Plaza', null, 'Telukpakedai');
insert into address (street, postal_code, city) values ('4580 Carey Court', null, 'Vágia');
insert into address (street, postal_code, city) values ('2243 Shoshone Center', null, 'Sarata');
insert into address (street, postal_code, city) values ('625 Myrtle Park', '92848 CEDEX', 'Rueil-Malmaison');
insert into address (street, postal_code, city) values ('884 Ludington Plaza', '38-116', 'Gwoźnica Górna');
insert into address (street, postal_code, city) values ('9056 Doe Crossing Park', '38-123', 'Wysoka Strzyżowska');
insert into address (street, postal_code, city) values ('855 Kennedy Lane', null, 'Hongyan');
insert into address (street, postal_code, city) values ('41720 Orin Hill', null, 'Broto');
insert into address (street, postal_code, city) values ('90 Trailsway Junction', '4615-099', 'Fonte');
